
############## custmer #################

############## spring cloud #################

eureka:
  datacenter: cloud
  environment: dev
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:123456@discovery:${server.port}/eureka/

############## spring boot #################

server:
  port: 8761

security:
  basic:
    enabled: false
  user:
    name: admin
    password: 123456

management:
  security:
    enabled: false

spring:
  application:
    name: discovery
