
############## custmer #################

############## spring cloud #################
      
eureka:
  client:
    serviceUrl: 
      defaultZone: http://admin:123456@discovery:8761/eureka/

############## spring boot #################

server:
  port: 8764
  tomcat:
    max-connections: 200
      
management:
  security:
    enabled: false
    
spring:
  application:
    name: gateway
