apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-demo1
  labels:
    name: k8s-demo1
spec:
  replicas: 2
  selector:
    name: k8s-demo1
  template:
    metadata:
      labels:
        name: k8s-demo1
    spec:
      containers:
      - name: k8s-demo1
        image: maxcd03-kube1.chinacloudapp.cn/test/k8s-demo1:v1
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 9876