
############## custmer #################

############## spring cloud #################

eureka:
  client:
    serviceUrl: 
      defaultZone: http://admin:123456@discovery:8761/eureka/

############## spring boot #################

server:
  port: 8762
    
security:
  basic:
    enabled: false
  user:
    name: admin
    password: 123456

management:
  security:
    enabled: false
    
spring:
  application:
    name: admin
  jackson:
    serialization:
      indent_output: true

endpoints:
  health:
    sensitive: false
