
############## custmer #################

############## spring cloud #################

eureka:
  client:
    serviceUrl: 
      defaultZone: http://admin:123456@127.0.0.1:8761/eureka/

############## spring boot #################

server:
  port: 8762
  
management:
  security:
    enabled: false
    
security:
  basic:
    enabled: false
  user:
    name: admin
    password: 123456

spring:
  application:
    name: admin
  jackson:
    serialization:
      indent_output: true

endpoints:
  health:
    sensitive: false
